[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
  VITE_SUPABASE_URL = "your_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  VITE_AI_API_KEY = "your_ai_api_key"
  VITE_AI_API_ENDPOINT = "your_ai_api_endpoint"
  VITE_API_BASE_URL = "your_api_base_url"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
